//gameInit();
global.money = 100;
global.wave = 0;
global.Health = global.maxHealth;
global.dragging = false;
global.selectedTower = noone;
global.intensity = 0;
global.Score = 0;
global.bossHealth = 0;
global.startwave = false;
global.bossStarted = false;
global.pause = false;
